### ISSUE TITLE
Make global-sidecar globally unique

### ISSUE THREAD

**Issue by pantianying** [slime-io/slime#11]
Global-sidecar is a bit like Ingress in architecture, in that we want to be globally unique, rather than having to deploy one for every namespace. This saves resources and makes the architecture simpler,Easier to operate.

**Comment by ydh926** [comment]
We can support this deployment architecture in slime-boot. However, if you use the globally unique global-sidecar, you need to bring the service namespace when calling the service.

**Comment by pantianying** [comment]
> We can support this deployment architecture in slime-boot. However, if you use the globally unique global-sidecar, you need to bring the service namespace when calling the service.

携带namespace信息能否在envoyfilter中完成，不需要用户关心
