### ISSUE TITLE
lazyload:  automatically get wormholeport from service port definition 

### ISSUE THREAD

**Issue by stanxing** [slime-io/slime#121]
**Is your feature request related to a problem? Please describe.**

After testing lazyload, I found I have to specify all wormhole ports in YAML explicitly to inject to_global_sidecar route, maybe is there a way to automatically get all port list?

**Describe the solution you'd like**
One possible solution is that watching service resources to generate a avaliable port list.

**Comment by YonkaFang** [comment]
In current impl slime generates global sidecar service CR before (re-)deploying lazyload, thus it's not easy to achieve what y want.
We will refactor the global sidecar implementation mechanism in a near future release so that we can get rid of this dependency.
At that time, the wormholeport will no longer be required.

**Comment by cywang1905** [comment]
Unfortunately, although we have released a new version of Lazyload module that addresses issues such as customization of components, ports still need to be explicitly specified. The main problem is that when Lazyload is first enabled, the listener is removed if a port is not served. When the listener is missing, the route_config is removed together. Even if the access corresponding to this port is initiated again, the call relationship record cannot be achieved through lazyload as listener is removed, and it goes directly to PassthroughCluster. We will continue to try to resolve this issue.

很不幸，虽然我们已经发布了新的懒加载版本，解决了定制化组件等问题，但是端口仍然需要显式指定。主要问题在于，刚启用懒加载时，如果某个端口没有服务，listener会被去除。缺少listener后，route_config一起删除。即使再发起对这个端口对应的访问，由于缺少listener，无法通过懒加载实现调用关系记录，直接走到PassthroughCluster。我们会继续尝试解决此问题。

**Comment by cywang1905** [comment]
Layzload of the latest code now supports automatic management of service ports, and the wormwholePort param can no longer be specified, details at https://github.com/slime-io/slime/pull/157.
Related documentation will be added in the next version
