### ISSUE TITLE
Please add Slime to the Istio ecosystem page!

### ISSUE THREAD

**Issue by craigbox** [slime-io/slime#126]
PTAL at https://istio.io/latest/about/ecosystem/#integrations and https://github.com/istio/community/blob/master/CONTRIBUTING.md#promote-your-company-on-istioio. and put information about Slime on the istio.io website.

**Comment by YonkaFang** [comment]
Okay we'll get started on that soon. Thanks for your advice.

**Comment by YonkaFang** [comment]
@craigbox I've opened the [merge request](https://github.com/istio/istio.io/pull/10576). Plz help review it.

**Comment by YonkaFang** [comment]
Close as relevant PR has been merged. Thanks again.
