### ISSUE TITLE
slime boot install error when follow lazy load tutorials 

### ISSUE THREAD

**Issue by nonumber1989** [slime-io/slime#192]
**Bug description**
we want to try lazy load  but  found that slime boot install error when follow the tutorials
**Affected sub-moudle (please put an X in all that apply)**

[ X ] Slime Boot

**Steps to reproduce the bug**
`$ export latest_tag=$(curl -s https://api.github.com/repos/slime-io/lazyload/tags | grep 'name' | cut -d\" -f4 | head -1)
`
`$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/slime-io/lazyload/$latest_tag/install/samples/lazyload/easy_install_lazyload.sh)"
`
![image](https://user-images.githubusercontent.com/4054215/194839556-389f593d-6357-4319-99f3-71bc96c87fc9.png)

{"level":"error","ts":1665395259.1904366,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"SlimeBoot.config.netease.com","error":"no matches for kind \"SlimeBoot\" in version \"config.netease.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/source/source.go:127"}
{"level":"error","ts":1665395259.1907156,"logger":"controller-runtime.manager.controller.slimeboot-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for slimeboot-controller caches to sync: no matches for kind \"SlimeBoot\" in version \"config.netease.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:195\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/manager/internal.go:696"}
{"level":"error","ts":1665395259.1911843,"logger":"cmd","msg":"Manager exited non-zero.","Namespace":"","error":"failed to wait for slimeboot-controller caches to sync: no matches for kind \"SlimeBoot\" in version \"config.netease.com/v1alpha1\"","stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/helm-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/helm-operator/run/cmd.go:74\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897\nmain.main\n\t/workspace/cmd/helm-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}

**Comment by cywang1905** [comment]
It seems like lack of crd `kind "SlimeBoot" in version "config.netease.com/v1alpha1"`. But I try again, cannot get the same result.
The proper result will be like this
![2022-10-11 12-18-46 的屏幕截图](https://user-images.githubusercontent.com/22366230/194996350-221e758a-a1d7-4a53-a4b7-1e5ff8779fce.png)

Anyway, you can also try apply crd manually, here [lazyload related crd](https://raw.githubusercontent.com/slime-io/lazyload/v0.3.0/install/init/crds.yaml)
