### ISSUE TITLE
smartlimiter: customized reponse header

### ISSUE THREAD

**Issue by MouceL** [slime-io/slime#243]
**whatever you want to say to slime developers**

the reponse headers shound be modifiable in `smartlimiter`,  just like response_headers_to_add in

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#id1

**Comment by jk-tonycui** [comment]
I would like to work on it, please assign to me.

**Comment by YonkaFang** [comment]
> I would like to work on it, please assign to me.

Glad you can participate, you can ask @MouceL  any development process-related questions or communicate in the WeChat group

**Comment by jk-tonycui** [comment]
I have made a PR, please help to review.

**Comment by cywang1905** [comment]
thx, we will handle soon
