### ISSUE TITLE
Can't setup local environment  by the README

### ISSUE THREAD

**Issue by nonumber1989** [slime-io/slime#29]
**Can't setup local environment by the README**

I have checked the README and found that some  componets'  version is wrong;  i don't kown which verison is the latest working one .

Please help to correct the README 
THX

**Comment by cywang1905** [comment]
> **Can't setup local environment by the README**
> 
> I have checked the README and found that some componets' version is wrong; i don't kown which verison is the latest working one .
> 
> Please help to correct the README
> THX


We have updated the README. You can try it again now.
