### ISSUE TITLE
Fence模块打开后，相关组件没有运行成功

### ISSUE THREAD

**Issue by liuqi-sun** [slime-io/slime#30]
使用Slime的配置懒加载功能需打开Fence模块，同时安装附加组件，如下：
![image](https://user-images.githubusercontent.com/48784730/124445932-8fb73d80-ddb2-11eb-8b6a-76e8d67ee737.png)

**Comment by cywang1905** [comment]
我们更新了slime-boot的helm版本，已经修复了此问题。你可以参照新的README，再次尝试下。
We have updated the helm version of slime-boot and fixed this problem. You can try it again by the step of README.
