### ISSUE TITLE
After servicefence is created, no sidecar is generated

### ISSUE THREAD

**Issue by liuqi-sun** [slime-io/slime#31]
采用普罗米修斯 上报调用链方式：
![image](https://user-images.githubusercontent.com/48784730/126431065-f6eaf0e9-cea5-4465-9e45-7ca1f581198e.png)

lazyload process is no any print
![image](https://user-images.githubusercontent.com/48784730/126431223-c55b45cc-de67-48c6-9b5f-f189dc334661.png)

**Comment by cywang1905** [comment]
我们更新了slime-boot的helm版本，已经修复了此问题。你可以参照新的README，再次尝试下。
We have updated the helm version of slime-boot and fixed this problem. You can try again by the step of README.
