### ISSUE TITLE
On lazyload prometheus mode, lazyload log error

### ISSUE THREAD

**Issue by Patrick0308** [slime-io/slime#364]
**Bug description**
I tested the [lazyload cluster prometheus example](https://raw.githubusercontent.com/slime-io/slime/v0.7.0/staging/src/slime.io/slime/modules/lazyload/install/samples/lazyload/slimeboot_cluster_prometheus.yaml). It can't work successfully.

On lazyload prometheus mode, the global sidecar's svc is not be created.
And lazyload pod log error. See below:
![image](https://github.com/slime-io/slime/assets/5486149/a8250884-309d-416b-b794-0adf2ffefd2d)

**Affected sub-moudle (please put an X in all that apply)**

[x] Configuration Lazy Loading
[ ] Http Plugin Management
[ ] Adaptive Ratelimit
[ ] Slime Boot

**Steps to reproduce the bug**

**Comment by MouceL** [comment]
I will follow up on the above issues.

we are currently fading the use of the prometheus method
