### ISSUE TITLE
lazyload controllers keep writing servicefence when working with multi replicas

### ISSUE THREAD

**Issue by QuentinYo** [slime-io/slime#365]
**Bug description**
lazyload controllers keep writing servicefence when working with multi replicas and it has different content wrote into servicefence.

lazyload yaml:
[lazyload-slimeboot.yaml.txt](https://github.com/slime-io/slime/files/11487121/lazyload-slimeboot.yaml.txt)

log from lazyload controller:
[err.log](https://github.com/slime-io/slime/files/11487110/err.log)

**Affected sub-moudle (please put an X in all that apply)**

[ ] Configuration Lazy Loading
[ ] Http Plugin Management
[ ] Adaptive Ratelimit
[ ] Slime Boot

**Steps to reproduce the bug**

**Comment by QuentinYo** [comment]
![image](https://github.com/slime-io/slime/assets/7312478/af274ea8-771f-46e7-90a8-093fbf7e9bc9)
![image](https://github.com/slime-io/slime/assets/7312478/6127942d-e437-4a9a-acb3-7abcf261ec3e)
![image](https://github.com/slime-io/slime/assets/7312478/7f9f24ec-e834-4f3c-848d-f73b7cafc1ae)

**Comment by MouceL** [comment]
use `enable-leader-election` in v0.7.1

enableLeaderElection is added in last commit

**Comment by MouceL** [comment]
> ![image](https://user-images.githubusercontent.com/7312478/238628315-af274ea8-771f-46e7-90a8-093fbf7e9bc9.png) ![image](https://user-images.githubusercontent.com/7312478/238628418-6127942d-e437-4a9a-acb3-7abcf261ec3e.png) ![image](https://user-images.githubusercontent.com/7312478/238628471-7f9f24ec-e834-4f3c-848d-f73b7cafc1ae.png)

use enable-leader-election in v0.7.1

enableLeaderElection is added in last commit

**Comment by MouceL** [comment]
use enable-leader-election in v0.7.1  @QuentinYo 

enableLeaderElection is added in last commit
