### ISSUE TITLE
i9s 集成大语言模型能力

### ISSUE THREAD

**Issue by believening** [slime-io/slime#378]
**问题背景**

i9s 集成 chatgpt 提供网格问题诊断能力。

**您想要的解决方案**

istio 社区提供了 [istioctl analyze](https://istio.io/latest/docs/ops/diagnostic-tools/istioctl-analyze) 诊断工具用于分析 istio 配置的潜在问题。

社区的 [k8sgpt ](https://github.com/k8sgpt-ai/k8sgpt) 可以收集和并使用生成式 AI 辅助诊断集群中的问题。

**您考虑过的替代方案**

**额外的上下文**

**Comment by MouceL** [comment]
如果是一个离线的二进制包，就比较容易集成
