### ISSUE TITLE
slime-boot 怎么生成，用什么命令

### ISSUE THREAD

**Issue by liuqi-sun** [slime-io/slime#38]
![image](https://user-images.githubusercontent.com/48784730/130001434-d0913c2a-d9f6-46ea-a60d-d78a74434761.png)

我想修改模板里的global-sidecar的镜像，修改完后，怎么构建新的slime-boot

**Comment by cywang1905** [comment]
你可以使用slime/slime-boot/deploy.sh，修改deploy.sh中的HUB值，制作新slime-boot镜像

**Comment by liuqi-sun** [comment]
> 你可以使用slime/slime-boot/deploy.sh，修改deploy.sh中的HUB值，制作新slime-boot镜像

好的，我看到最近增加了这个deploy.sh脚本了，之前的项目是没有的。
