### ISSUE TITLE
global-sidecar fail

### ISSUE THREAD

**Issue by liuqi-sun** [slime-io/slime#40]
![image](https://user-images.githubusercontent.com/48784730/130211251-503b3a92-f555-4b2e-8720-19078fab533e.png)

kubectl logs -f global-sidecar-68cff87588-72qcg -n liuqi-test
![image](https://user-images.githubusercontent.com/48784730/130211317-2a89810f-e72d-47e3-a63c-874670daade7.png)

kubectl describe pod  global-sidecar-68cff87588-72qcg -n liuqi-test
![image](https://user-images.githubusercontent.com/48784730/130211840-d817fd37-a615-47c9-b898-8d9d4e933423.png)

**Comment by YonkaFang** [comment]
使用上的问题到qq/slack交流吧。 很多都是操作问题而不是bug噢。 开issue比较噪音。
谢谢配合。

**Comment by liuqi-sun** [comment]
> 使用上的问题到qq/slack交流吧。 很多都是操作问题而不是bug噢。 开issue比较噪音。
> 谢谢配合。
你好 是qq号，slack吗？

**Comment by YonkaFang** [comment]
@liuqi-sun readme（主页）最末有联系信息

**Comment by YonkaFang** [comment]
related to #47
