### ISSUE TITLE
slime-boot imagePullSecrets 未定义

### ISSUE THREAD

**Issue by Patrick0308** [slime-io/slime#421]
**问题描述**
在 helm template 中有 imagePullSecrets ，但是 slime-boot 没有定义 imagePullSecrets

**影响的子模块(在下面列表中打'X')**

- [ ] 配置懒加载
- [ ] 插件管理
- [ ] 智能限流
- [ ] 注册仓库
- [ ] 安装Boot

**重现问题的步骤**

**Comment by MouceL** [comment]
https://github.com/slime-io/slime/blob/master/framework/apis/config/v1alpha1/slime_boot.proto#L27

https://github.com/slime-io/slime/blob/master/boot/helm-charts/slimeboot/templates/deployment.yaml#L40

**Comment by Patrick0308** [comment]
最新已经修复
