### ISSUE TITLE
to_global_sidecar envoyfilter match proxyVersion 

### ISSUE THREAD

**Issue by Patrick0308** [slime-io/slime#424]
**问题背景**

to_global_sidecar envoyfilter 在新版与旧版中有存在兼容问题，istio 升级时，存在有一部分 sidecar 兼容有一部分 sidecar 不兼容。

**您想要的解决方案**
to_global_sidecar 添加 proxyVersion 匹配，只应用于高版本的 sidecar

**您考虑过的替代方案**

**额外的上下文**

**Comment by MouceL** [comment]
从版本升级兼容性方面考虑, 确实很重要

我们前段时间在plugin中也加了类似功能

**Comment by Patrick0308** [comment]
https://github.com/Patrick0308/slime/blob/feat-proxy-version/staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml#L155
不太清楚，这里为什么把 global-sidecar 的 version 设置为了 999.0.0，这个导致 proxyVersion 的匹配有点问题

**Comment by MouceL** [comment]
> https://github.com/Patrick0308/slime/blob/feat-proxy-version/staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml#L155 不太清楚，这里为什么把 global-sidecar 的 version 设置为了 999.0.0，这个导致 proxyVersion 的匹配有点问题

这个是由于社区版本istio安装后，会有一些关于metadata/stats 的envoyfilter, 并带有proxyVersion

之前发现这些会影响到懒加载，所以加了个999, 表示这些永远match不了

**Comment by YonkaFang** [comment]
> 

accesslog模式下不渲染这个即可，不用额外开关

**Comment by MouceL** [comment]
https://github.com/slime-io/slime/pull/426
