### ISSUE TITLE
lazyload不生效

### ISSUE THREAD

**Issue by cwww3** [slime-io/slime#465]
**问题描述**
服务的sidercar日志中有警告,可以生成servicefence和sidercar，但是domain里没有依赖的其他服务。
**影响的子模块(在下面列表中打'X')**

- [x] 配置懒加载
- [ ] 插件管理
- [ ] 智能限流
- [ ] 注册仓库
- [ ] 安装Boot

**重现问题的步骤**

istio 1.15
k8s 1.19
2023-12-06T07:26:12.183414Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: field 'ENVIRONMENT(POD_NAMESPACE)' not supported as custom header

**Comment by MouceL** [comment]
这个问题是由于envoy版本还不支持env方式添加header

你用的是那个版本slime镜像

**Comment by cwww3** [comment]
> 这个问题是由于envoy版本还不支持env方式添加header
> 
> 你用的是那个版本slime镜像

v.0.8.2

**Comment by MouceL** [comment]
> > 这个问题是由于envoy版本还不支持env方式添加header
> > 你用的是那个版本slime镜像
> 
> v.0.8.2

在slimeboot的general下指定

`addEnvHeaderViaLua: true`  用lua方式代替env方式

**Comment by cwww3** [comment]
> > > 这个问题是由于envoy版本还不支持env方式添加header
> > > 你用的是那个版本slime镜像
> > 
> > 
> > v.0.8.2
> 
> 在slimeboot的general下指定
> 
> `addEnvHeaderViaLua: true` 用lua方式代替env方式

好 我试试。还有其他解决方案吗

**Comment by MouceL** [comment]
> > > > 这个问题是由于envoy版本还不支持env方式添加header
> > > > 你用的是那个版本slime镜像
> > > 
> > > 
> > > v.0.8.2
> > 
> > 
> > 在slimeboot的general下指定
> > `addEnvHeaderViaLua: true` 用lua方式代替env方式
> 
> 好 我试试。还有其他解决方案吗

没有其他方式了，部署时候指定

**Comment by cwww3** [comment]
> > > > > 这个问题是由于envoy版本还不支持env方式添加header
> > > > > 你用的是那个版本slime镜像
> > > > 
> > > > 
> > > > v.0.8.2
> > > 
> > > 
> > > 在slimeboot的general下指定
> > > `addEnvHeaderViaLua: true` 用lua方式代替env方式
> > 
> > 
> > 好 我试试。还有其他解决方案吗
> 
> 没有其他方式了，部署时候指定

可以了。  是istio版本低了吗，导致不兼容
