### ISSUE TITLE
global-sidecar支持nodeSelector或者节点亲和性等功能

### ISSUE THREAD

**Issue by erenliu168** [slime-io/slime#474]
**问题背景**
环境中存在多种cpu架构的k8s节点，目前公司未使用多架构容器镜像（以镜像名称区分架构），未指定nodeSelector或者节点亲和性时，global-sidecar自动部署在了arm节点上（指定的镜像为x86架构），导致pod crash。
**您想要的解决方案**
slimeboot cr中暴露指定global-sidecar nodeSelector或者节点亲和性的配置字段
**您考虑过的替代方案**
1、修改charts文件重新编译，但没有有效的可配置手段，不改代码的情况下只能手动修改yaml文件。
2、修改加载charts文件添加入口以及update_resource.go中加载charts文件的逻辑，对charts文件进行渲染（需要考虑配置的获取途径，如slimeboot crd中增加字段，或者直接继承lazyload模块的nodeSelector也行）
**额外的上下文**

**Comment by MouceL** [comment]
好的 最近会加上去的

**Comment by erenliu168** [comment]
请问该特性合入的具体时间现在有规划吗？
