### ISSUE TITLE
Ftr: expose more deployment information to SlimeBoot

### ISSUE THREAD

**Issue by pantianying** [slime-io/slime#6]
As mentioned, there are many deployment configurations that require user customization.
such as：
https://github.com/slime-io/slime/blob/42f74183acc72d40f76a837db9dfe34fea182fb5/slime-boot/helm-charts/slimeboot/templates/report-server.yaml#L117

the image info should be exposed to SlimeBoot

**Comment by ydh926** [comment]
Fixed ，slime-boot will continue to optimize，thanks for your suggestion！
