### ISSUE TITLE
Allow values.yaml mounted from configmap to override slimeboot values

### ISSUE THREAD

**Issue by YonkaFang** [slime-io/slime#83]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

User can choose to add a configmap whose content is like `values.yaml` to override part of original `values.yaml` in slimeboot image.

**Describe alternatives you've considered**

**Additional context**

**Comment by cywang1905** [comment]
Docs about slimeboot default value and method to override partially
https://github.com/slime-io/slime/blob/master/doc/en/slime-boot.md#slimeboot-default-value-instruction-and-replacement-method
